module.exports = {
    TOKEN_EXPIRED       : 'TOKEN_EXPIRED',
    WRONG_TOKEN         : 'WRONG_TOKEN',
    WRONG_SCREENS_TOKEN : 'WRONG_SCREENS_TOKEN',
    PERMISSION_DENIED   : 'PERMISSION_DENIED'
};
